### ISSUE TITLE
Not working on 1.20.6

### ISSUE THREAD

**Issue by andrewkm** [pustinek/ItemFilter#12]
@pustinek not working on Paper 1.20.6 Build 145
```
[22:04:22] [Server thread/INFO]: [ItemFilter] Enabling ItemFilter v${version}
[22:04:22] [Server thread/ERROR]: Error occurred while enabling ItemFilter v${version} (Is it up to date?)
java.lang.NoClassDefFoundError: fr/minuskube/inv/InventoryManager
	at ItemFilter-2.1.2.jar/me.pustinek.itemfilter.ItemFilterPlugin.onEnable(ItemFilterPlugin.java:102) ~[ItemFilter-2.1.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: fr.minuskube.inv.InventoryManager
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 13 more
[22:04:22] [Server thread/INFO]: [ItemFilter] Disabling ItemFilter v${version}
[22:04:22] [Server thread/ERROR]: Error occurred while disabling ItemFilter v${version}
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:550) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:250) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at ItemFilter-2.1.2.jar/me.pustinek.itemfilter.users.UserManager.<init>(UserManager.java:29) ~[ItemFilter-2.1.2.jar:?]
	at ItemFilter-2.1.2.jar/me.pustinek.itemfilter.ItemFilterPlugin.getUserManager(ItemFilterPlugin.java:173) ~[ItemFilter-2.1.2.jar:?]
	at ItemFilter-2.1.2.jar/me.pustinek.itemfilter.ItemFilterPlugin.onDisable(ItemFilterPlugin.java:86) ~[ItemFilter-2.1.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by pustinek** [comment]
You probably just copied the wrong .jar file when you compiled it. The correct one is with dependencies shadowed (without the version number appended to the name).

**Comment by andrewkm** [comment]
> You probably just copied the wrong .jar file when you compiled it. The correct one is with dependencies shadowed (without the version number appended to the name).

Oh nvm, looks like we'll be running a private fork from now on since you basically removed our player's most loved feature, category GUI's lol. Thanks for the plugin though! Definitely a nifty little tool. :)
